services:
  splattrack:
    image: gheja/splattrack:0.1.1
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    devices:
      - nvidia.com/gpu=all
    volumes:
      - ./workspace:/workspace
