services:
  splattrack:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: splattrack:0.1.1
    env_file: .env
    devices:
      - nvidia.com/gpu=all
    volumes:
      - ./workspace:/workspace
